apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-proj
  labels:
     app: wedding-proj

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wedding-proj

  template:
    metadata:
      labels:
        app: wedding-proj
    spec:
      containers:
      - name: httpd-proj
        image: divakar2201/wedding-proj:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

